version: '2.4'
services:
  db:
    image: 'lapicidae/mariadb-epglv:latest'
    container_name: mariadb-epglv
    volumes:
      - './MySQL:/var/lib/mysql:rw'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - EPGD_RECOMMEND=yes
      - TZ=Europe/Berlin
    command: mysqld
    entrypoint: /mariadb-epglv.sh
    network_mode: bridge
    ports:
      - '3306:3306'
    restart: unless-stopped
